# Generated by Django 3.1.3 on 2020-12-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
    ]
