# Generated by Django 3.1 on 2021-01-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0003_auto_20210101_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pincode',
            field=models.CharField(choices=[('400601', '400601'), ('400602', '400602'), ('400604', '400604'), ('400608', '400608')], default='400601', max_length=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
