# Generated by Django 3.1 on 2021-01-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0004_auto_20210102_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='fullname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
